version: '3.8'

services:
  prauto-scraper:
    build: .
    container_name: prauto-scraper
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
    environment:
      - HEADLESS=true
      - TZ=America/Argentina/Buenos_Aires
    restart: unless-stopped
    # Para ejecutar manualmente:
    # docker-compose run --rm prauto-scraper
    
    # Para ejecutar con cron (descomenta la línea siguiente):
    # profiles: ["cron"]

  # Servicio opcional para scheduling con cron
  scraper-cron:
    build: .
    container_name: prauto-scraper-cron
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./crontab:/etc/cron.d/scraper-cron
    environment:
      - HEADLESS=true
      - TZ=America/Argentina/Buenos_Aires
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y cron &&
        chmod 0644 /etc/cron.d/scraper-cron &&
        crontab /etc/cron.d/scraper-cron &&
        cron -f
      "
    profiles: ["cron"]